name: tapdevelops_core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  meta: ^1.10.0
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
